#!/bin/bash

if [[ $1 < 20 ]]; then
   eww update brightness_icon="󰃚"
elif [[ $1 < 40 ]]; then
   eww update brightness_icon="󰃛"
elif [[ $1 < 60 ]]; then
   eww update brightness_icon="󰃜"
elif [[ $1 < 80 ]]; then
   eww update brightness_icon="󰃝"
else
   eww update brightness_icon="󰃞"
fi
